# Generated by Django 2.0.4 on 2018-05-14 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20180510_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 5, 20, 58, 803230, tzinfo=utc)),
        ),
    ]
