# Generated by Django 2.0.4 on 2018-05-14 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180514_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 14, 8, 29, 52, 184032, tzinfo=utc)),
        ),
    ]
