# Generated by Django 2.0.4 on 2018-05-16 06:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180514_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 16, 6, 24, 10, 460226, tzinfo=utc)),
        ),
    ]
