# Generated by Django 2.0.4 on 2018-05-17 07:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20180516_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 17, 7, 0, 29, 419675, tzinfo=utc)),
        ),
    ]
